// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf_MM7ZKtEwnlH-OT1Uh4VSP_0VkoIk68',
    appId: '1:497628810314:web:b4fd59694cf7dbbb6feab3',
    messagingSenderId: '497628810314',
    projectId: 'tobeto-2a-49e31',
    authDomain: 'tobeto-2a-49e31.firebaseapp.com',
    storageBucket: 'tobeto-2a-49e31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtm17Jgux-ALAypEGlMRMEEvHu0cvq8vo',
    appId: '1:497628810314:android:0982ad8eac2b33736feab3',
    messagingSenderId: '497628810314',
    projectId: 'tobeto-2a-49e31',
    storageBucket: 'tobeto-2a-49e31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbOJiYHrR2PrhAMk2zxJ8BmXSE2hT8RA4',
    appId: '1:497628810314:ios:84bcd5420e78b1856feab3',
    messagingSenderId: '497628810314',
    projectId: 'tobeto-2a-49e31',
    storageBucket: 'tobeto-2a-49e31.appspot.com',
    iosBundleId: 'com.example.firebaseintro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbOJiYHrR2PrhAMk2zxJ8BmXSE2hT8RA4',
    appId: '1:497628810314:ios:84bcd5420e78b1856feab3',
    messagingSenderId: '497628810314',
    projectId: 'tobeto-2a-49e31',
    storageBucket: 'tobeto-2a-49e31.appspot.com',
    iosBundleId: 'com.example.firebaseintro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf_MM7ZKtEwnlH-OT1Uh4VSP_0VkoIk68',
    appId: '1:497628810314:web:517122987cd428e96feab3',
    messagingSenderId: '497628810314',
    projectId: 'tobeto-2a-49e31',
    authDomain: 'tobeto-2a-49e31.firebaseapp.com',
    storageBucket: 'tobeto-2a-49e31.appspot.com',
  );

}